apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: Longhorn
metadata:
  name: longhorn
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
    defaultSettings:
      backupTarget: ""
      createDefaultDiskLabeledNodes: true
